# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    - id: isort
      args: [--profile, black]
-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
    - id: interrogate
      args: [-i, --fail-under=80]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
